DELIMITER //
DROP PROCEDURE IF EXISTS `opening_closing`;
CREATE PROCEDURE `opening_closing` ()
BEGIN
    	SELECT CUST_NAME, GRADE
	FROM customer
	WHERE OPENING_AMT + RECEIVE_AMT > 10000;
END//
DELIMITER;